### PR TITLE
fix: Handle USER_SIGNED_OUT event the same like USER_UNLOADED

### LINKED ISSUE #972: Single Sign out browser level.keycloak
Thanks for wonderful library. I used for Keycloak integration. Overall, it's been working well. I've implemented local storage for storing data. However, when I log out in one tab, it doesn't automatically log me out in other open tabs. If I refresh the page, it correctly redirects to the login page. The issue arises when I perform actions without refreshing; it results in errors. I'm looking for a solution to achieve browser-level logout. Thanks.

### PR DESCRIPTION
**Pull request by PSanetra**
We experienced the same issue like #972 and as far as I see this is caused by the currently unhandled userSignedOut event.

Fixes #972

### CODE REVIEW

**Review by pamapa — APPROVED** [review]

**Comment by pamapa** [comment]
good point, thanks for contributing!

**Comment by PSanetra** [comment]
@pamapa Thank you for the quick reaction! Do you have an ETA when this change will be available in an release?

**Comment by pamapa** [comment]
@PSanetra It will be part of v3, depending on oidc-client-ts v3,  end of January

**Comment by PSanetra** [comment]
@pamapa yes I think it makes sense to get an early release candidate to confirm that everything works as expected with that release

**Pull request merged**
