### PR TITLE
expose signinCallback for native applications

### LINKED ISSUE #1216: Possibility to access signinCallback function?
I have a website that is also converted into an app via Capacitor. The login on the website works without any problems. But not for the native app.
There is a hook for Capacitor when the redirect URL is called from the auth provider. 
```
    CapApp.addListener("appUrlOpen", async ({ url }) => {
        // TODO: handle URL
    });
```

A URL is returned that contains the code & session_state. I would need to call a function there to handle the URL (not window.location.href). Is there a way to do this?

In [auth0-react](https://github.com/auth0/auth0-react) there is a function called "handleRedirectCallback(url)" that does just that.

### PR DESCRIPTION
**Pull request by tmo207**
Closes/fixes #1216  #1145 

Capacitor apps do not trigger signinCallback when returning from the browser to the app. By calling signinCallback manually the user is able to finish authenticaion.

Example:

    CapApp.addListener("appUrlOpen", async ({ url }) => {
        // TODO: handle URL
        ...
        await auth.callSigninCallback('/some-path' + authParams);
       ...
    });

The problem here is that the AuthState is not updated after the call. The reducer is called with the correct values (isLoading: false, isAuthenticated: true), but the native app needs a manual reload to update the AuthState. Any idea why this might be @pamapa ?

### Checklist

- [x] This PR makes changes to the public API 
- [x] I have included links for closing relevant issue numbers

### CODE REVIEW

**Comment by pamapa** [comment]
> The problem here is that the AuthState is not updated after the call. The reducer is called with the correct values (isLoading: false, isAuthenticated: true), but the native app needs a manual reload to update the AuthState. Any idea why this might be?

This MR is more a workaround than a fix.

The reducer creates a new state, which should be propagated via `useReducer`, respectively via `useAuth` into the application. Assuming that within the application the state is not cached (useMemo) i would assume that code element would be re-rendered...

**Comment by taszilvo** [comment]
Hey guys @tmo207 @pamapa! I am still curious about the potential fix for the issue with capacitor apps. What happened with this PR? Could you somehow solve the bug at the end?

**Comment by pamapa** [comment]
@taszilvo if you really need it, there is no other way we can add something like this. The name of the new exposed function would be `signinCallback`. On the other hand if you create the `UserManager` object outside and pass it into `AuthProvider`, you can do whatever you like on that object...

**Comment by tmo207** [comment]
You're right, passing the UserManager from outside and calling signInCallback on it works. Thanks for the help!

**Comment by Canuckaholic** [comment]
I also would have liked to have seen this PR merged or worked on as a fix for Capacitor apps...

**Pull request closed without merging**
