### PR TITLE
feat: Dispatch errors to state in AuthProvider

### PR DESCRIPTION
**Pull request by ChrisL108**
- Errors during authentication navigation methods are now caught and dispatched to the state for better error handling and user feedback.

We had an issue where an invalid `authority` url was passed to AuthProvider and needed a way to catch this.

### Checklist

- [ ] This PR makes changes to the public API 
- [ ] I have included links for closing relevant issue numbers

### CODE REVIEW

**Comment by pamapa** [comment]
patch looks good, can you please make the lint/test pass?

**Comment by ChrisL108** [comment]
@pamapa addressed the linting issues. All tests are passing, although I do see quite a few console.errors that are happening with or without my changes, fyi.

**Comment by pamapa** [comment]
> All tests are passing, although I do see quite a few console.errors that are happening with or without my changes, fyi.

Yes, the tests originally did not have console errors, but after updating npm packages used for testing suddenly we had those. Maybe someone finds time to fix them.

**Comment by pamapa** [comment]
This exception is now accessible via `auth.error`. As this is handled internally via a reducer, you can not immediately access the error object, but in you render code:
```tsx
if (auth.error) {
    return <div>Oops... {auth.error.message}</div>;
}
```

**Pull request merged**
