### PR TITLE
Iss 566

### LINKED ISSUE #566: withAuth overwrites props instead of adding `props.auth` as documented ?
other relevant packages
```js
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.3.0",
```

example
```js
import React, { Component } from 'react';
import { Button, Grid, Typography } from '@mui/material';
import { withAuth } from 'react-oidc-context';

class LoginPage extends Component {
  constructor(props) {
    super(props);
    this.handleLogin = this.handleLogin.bind(this);
    this.handleLogout = this.handleLogout.bind(this);
  }

  handleLogin(event) {
    // ...
  }

  handleLogout(event) {
    // ...
  }

  render() {
    console.log(JSON.stringify(this.props))
    if (this.props.auth.isAuthenticated) {
      return (
        <form onSubmit={this.handleLogout}>
          <Grid container direction="row" justify="flex-end" alignItems="center">
            <Typography variant="h6" color="inherit">{this.props.auth.user?.profile.email}</Typography>
            <Button variant="outlined" color="secondary" type="submit">Logout</Button>
          </Grid>
        </form>
      );
    }
    else {
      return (
        <form onSubmit={this.handleLogin}>
          <Grid container direction="column" justify="center" alignItems="center">
            <Grid item xs={3}>
              <Button variant="contained" color="primary" type="submit">Login</Button>
            </Grid>
          </Grid>
        </form>
      );
    }
  }
}

export default withAuth(LoginPage);
```

Expected behavior is: `props` contains `auth` object

Actual behavior: Error message as `auth` evaluates to undefined. Printing `this.props` shows

```
{"isLoading":false,"isAuthenticated":false,"user":null,"settings":{"authority":"blahblah","metadataUrl":"...","client_id":"...
```
etc...

### PR DESCRIPTION
**Pull request by akotranza**
Closes/fixes #566 

### Checklist

- [x] This PR makes changes to the public API 
- [x] I have included links for closing relevant issue numbers

### CODE REVIEW

**Comment by pamapa** [comment]
build error:
```
npm run build


> react-oidc-context@2.2.0 build
> node scripts/build.js && npm run build-types


> react-oidc-context@2.2.0 build-types
> tsc --emitDeclarationOnly && api-extractor run


api-extractor 7.33.5  - https://api-extractor.com/

Using configuration from ./api-extractor.json
Analysis will use the bundled TypeScript version 4.8.4
Warning: You have changed the public API signature for this project. Please copy the file "temp/react-oidc-context.api.md" to "docs/react-oidc-context.api.md", or perform a local build (which does this automatically). See the Git repo documentation for more info.
```

**Comment by akotranza** [comment]
> build error:
> 
> ```
> npm run build
> 
> 
> > react-oidc-context@2.2.0 build
> > node scripts/build.js && npm run build-types
> 
> 
> > react-oidc-context@2.2.0 build-types
> > tsc --emitDeclarationOnly && api-extractor run
> 
> 
> api-extractor 7.33.5  - https://api-extractor.com/
> 
> Using configuration from ./api-extractor.json
> Analysis will use the bundled TypeScript version 4.8.4
> Warning: You have changed the public API signature for this project. Please copy the file "temp/react-oidc-context.api.md" to "docs/react-oidc-context.api.md", or perform a local build (which does this automatically). See the Git repo documentation for more info.
> ```
> 
> Please provide changed `react-oidc-context.api.md` within this merge request...

Apologies. I misread the warning from `npm run build` as meaning it would automatically update that file, and it didn't show as modified.

**Review by pamapa — APPROVED** [review]

**Comment by pamapa** [comment]
thanks for contributing!

**Comment by akotranza** [comment]
glad to, thanks for this library! 😁

**Pull request merged**
